- name: set debconf to not save all v4 rules
  ansible.builtin.debconf:
    name: iptables-persistent
    question: iptables-persistent/autosave_v4
    value: false
    vtype: boolean

- name: set debconf to not save all v6 rules
  ansible.builtin.debconf:
    name: iptables-persistent
    question: iptables-persistent/autosave_v6
    value: false
    vtype: boolean

- name: install iptables-persistent package
  apt:
      name: iptables-persistent
      state: present
  notify: iptables_save

- iptables: '{{ item }}'
  with_items: '{{ iptables_rules }}'
  notify: iptables_save

- name: enable netfilter-persistent service
  service:
      name: netfilter-persistent
      enabled: yes
